name: push-ci-images

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: {}

jobs:
  build-push-image:

    permissions:
      contents: read
      id-token: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.25'
          check-latest: true
          cache: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2

      - uses: anchore/sbom-action/download-syft@da167eac915b4e86f08b264dbdbc867b61be6f0c # v0.20.5

      - uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          install-only: true

      - name: run goreleaser-snapshot
        run: |
          make goreleaser-snapshot
          docker images
          docker run ghcr.io/flowforge-sh/falcosidekick-ui:latest-amd64 -v
        env:
          GOPATH: /home/runner/go

      # Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to GHCR
        run: |
          docker push ghcr.io/flowforge-sh/falcosidekick-ui:latest-amd64
          docker push ghcr.io/flowforge-sh/falcosidekick-ui:latest-arm64
          docker push ghcr.io/flowforge-sh/falcosidekick-ui:latest-armv7
          docker manifest create --amend ghcr.io/flowforge-sh/falcosidekick-ui:latest ghcr.io/flowforge-sh/falcosidekick-ui:latest-amd64 \
            ghcr.io/flowforge-sh/falcosidekick-ui:latest-arm64 ghcr.io/flowforge-sh/falcosidekick-ui:latest-armv7
          docker manifest push --purge ghcr.io/flowforge-sh/falcosidekick-ui:latest

